[package]
name = "rustdefcon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.23.0" 
lazy_static = "1.4.0"
rand = "0.8.5"

