version: '3'
services:
  db:
    image: postgres:16.1
    environment:
      - POSTGRES_PASSWORD=uNaVeingee3Pheu8noh6
    volumes:
      - pgdata:/var/lib/postgresql/data
  db_tools:
    image: postgres:16.1
    command: bash
    volumes:
      - ./tmp:/tmp
    depends_on:
      - db
    environment: &db_conn
      PGUSER: postgres
      PGHOST: db
      PGPASSWORD: uNaVeingee3Pheu8noh6
      DATABASE_URL: postgresql://postgres:uNaVeingee3Pheu8noh6@db/postgres
  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
    depends_on:
      - db
    volumes:
      - ./:/app
    ports:
      - "4000:4000"
    environment:
      <<: *db_conn
      HTTP_PORT: 4000
  web-prod:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:uNaVeingee3Pheu8noh6@db/postgres
      HTTP_PORT: 4001
      SECRET_KEY_BASE: "aN/8DV9OiNgCe/outFn+ONXlfkoJfo7MxOmj3XDRDDG7RS/XvshxlAg2+YG+iPEv"
    ports:
      - "4001:4001"
    restart: "no"
    profiles:
      - "dont_lets_start"
  adminer:
    image: adminer
    ports:
      - "4432:8080"
    depends_on:
      - db

  solver:
    build: solver
    depends_on:
      - web
    restart: "no"
    profiles:
      - "dont_lets_start"
    volumes:
      - ./solver/tmp:/solver/tmp

volumes:
  pgdata:
